/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./App.{js,ts,tsx}', './components/**/*.{js,ts,tsx}'],

  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#221b00',
        background: '#f4faff',
        outline: '#7e7761',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#00504a',
        'on-secondary-container': '#600009',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-surface': '#111d23',
        'primary-fixed-dim': '#e8c41d',
        'surface-container-highest': '#d7e4ec',
        'tertiary-container': '#86ece1',
        'on-tertiary-fixed': '#00201d',
        surface: '#f4faff',
        'secondary-container': '#fc5d59',
        'inverse-on-surface': '#e6f3fb',
        'surface-bright': '#f4faff',
        'inverse-surface': '#263238',
        'secondary-fixed-dim': '#ffb3ae',
        'primary-container': '#fdd835',
        'on-background': '#111d23',
        'surface-container-low': '#e9f6fd',
        'secondary-fixed': '#ffdad7',
        'inverse-primary': '#e8c41d',
        'outline-variant': '#cfc6ac',
        'on-primary-container': '#715e00',
        'surface-container-high': '#ddeaf2',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#4c4733',
        'on-primary-fixed-variant': '#544600',
        'surface-tint': '#705d00',
        'surface-dim': '#cfdce4',
        secondary: '#b3272a',
        tertiary: '#006a63',
        'error-container': '#ffdad6',
        'surface-variant': '#d7e4ec',
        'on-secondary-fixed': '#410004',
        'on-tertiary-container': '#006b64',
        'tertiary-fixed': '#8ef4e9',
        'on-error-container': '#93000a',
        'surface-container': '#e3f0f8',
        primary: '#705d00',
        'primary-fixed': '#ffe16e',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#910816',
        'tertiary-fixed-dim': '#71d7cd',
        'surface-container-lowest': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        gutter: '16px',
        'section-gap': '64px',
        'container-margin': '24px',
        unit: '8px',
      },
      fontFamily: {
        'headline-md': ['Plus Jakarta Sans'],
        'display-lg-mobile': ['Plus Jakarta Sans'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'display-lg': ['Plus Jakarta Sans'],
        'label-bold': ['Inter'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-bold': ['14px', { lineHeight: '20px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
